### ISSUE TITLE
Callback implementation violates OOP principles

### ISSUE THREAD

**Issue by dimonik** [Frederikos/SampleAsyncHttpUsage#1]
Callback object com.test.asynchttpsampletemplate.network.listeners.Callback<T>
should not deal with UI items like View objects. This violates [SOLID](https://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29) software design principle.

It is Activity role to manage Views. So it should manage progressIndicator.

**Comment by Frederikos** [comment]
The key idea was to prevent duplicating this logic. And i didn't want to use JavaRx for this sample.
Now i have updated sample using Observable from new Android data binding for this.
